- name: Swarm init
  when: inventory_hostname == groups['manager'][0]
  register: __output_swarm
  community.docker.docker_swarm:
      state: present
      advertise_addr: "{{ ansible_default_ipv4.address }}:2377"

- name: Swarm clear
  when: inventory_hostname == groups['manager'][0]
  ansible.builtin.shell: |
      docker node ls | awk '/Down|Drain/ {print $1}' | while read NODE; do
      docker node rm $NODE --force
      done
